
export const store = [
  {
      "id": 1,
      "img_path": 'https://rukminim2.flixcart.com/image/850/1000/xif0q/mobile/n/i/d/-original-imagpgx4erjqnpzx.jpeg?q=90',
      "product_name": "Google Pixel 7a",
      "ratings": "10,332 Ratings",
      "ram": "8 GB RAM | 128 GB ROM",
      "display": "15.49 cm (6.1 inch) Display",
      "camera": "64MP+ 13MP | 13MP Front",
      "battery": "4300 mAh Battery",
      "processor": "Tensor G2 Processor",
      "warrenty": "12 Months Warrenty",
      "price": "35,999",
      "delivery_type": "Free delivery",
      "quantity": "",
      "bank_offer": "Bank Offer",
      "exchange": "",
      "off":"Extra ₹8000 off",
      "del_price":"₹69,999",
      "pack_fee":"+ ₹69 Secured Packaging Fee",
      "avl_off":"Available offers",
      
  },
  {
      "id": 2,
      "img_path": "https://m.media-amazon.com/images/I/61QiheOiObL._AC_UF894,1000_QL80_.jpg",
      "product_name": "OnePlus Nord 2T",
      "ratings": "2,617 Ratings",
      "ram": "12 GB RAM | 256 GB ROM",
      "display": "17.02 cm (6.7 inch) Display",
      "camera": "50MP Rear",
      "battery": "4500 mAh Battery",
      "processor": " Processor",
      "warrenty": "12 Months Warrenty",
      "price": "33,999",
      "delivery_type": "Free delivery",
      "quantity": "Only 1 left",
      "bank_offer": "Bank Offer",
      "exchange": ""
  },
  {
      "id": 3,
      "img_path": "https://cdn1.smartprix.com/rx-iVyp4t2Vm-w1200-h1200/Vyp4t2Vm.jpg",
      "product_name": "APPLE iphone 14",
      "ratings": "2,13,439 Ratings",
      "ram": "128 GB ROM",
      "display": "15.49 cm (6.1 inch) Display",
      "camera": "12MP + 12Mp Camera",
      "battery": "4300 mAh Battery",
      "processor": " A15 Bionic Chip",
      "warrenty": "12 Months Warrenty",
      "price": "57,449",
      "delivery_type": "Free delivery",
      "quantity": "",
      "bank_offer": "Bank Offer",
      "exchange": "Upto 42,000 off on Exchange"
  },
  {
      "id": 4,
      "img_path": "https://rukminim2.flixcart.com/image/850/1000/xif0q/mobile/4/x/0/-original-imagtnqjjfgxzpz4.jpeg?q=90",
      "product_name": "Samsung Galaxy S21",
      "ratings": "1,09,015 Ratings",
      "ram": "8GB RAM | 128 GB ROM",
      "display": "16.26 cm (6.1 inch) Display",
      "camera": "12MP + 12Mp Camera",
      "battery": "4500 mAh Battery",
      "processor": "Snapdagon 888 processor",
      "warrenty": "12 Months Warrenty",
      "price": "32,999",
      "delivery_type": "Free delivery",
      "quantity": "",
      "bank_offer": "Bank Offer",
      "exchange": ""
  },
  {
      "id": 5,
      "img_path": "https://rukminim2.flixcart.com/image/850/1000/xif0q/mobile/7/y/u/-original-imagqmtfu8gt62yv.jpeg?q=90",
      "product_name": "Xiaomi 12 Pro 5G",
      "ratings": "850 Ratings",
      "ram": "12GB RAM | 256 GB ROM",
      "display": "17.09 cm Display",
      "camera": "50MP + 50Mp Camera",
      "battery": "4600 mAh Battery",
      "processor": "Snapdagon 8 Gen processor",
      "warrenty": "12 Months Warrenty",
      "price": "41,999",
      "delivery_type": "Free delivery",
      "quantity": "Only 2 left",
      "bank_offer": "Bank Offer",
      "exchange": ""
  },
  {
      "id": 6,
      "img_path": "https://motorolaroe.vtexassets.com/arquivos/ids/157367-800-auto?width=800&height=auto&aspect=true",
      "product_name": "Razr 40 (Vanila)",
      "ratings": "2,617 Ratings",
      "ram": "8GB RAM | 256 GB ROM",
      "display": "17.53 cm Display",
      "camera": "64MP Rear Camera",
      "battery": "4200 mAh Battery",
      "processor": "Snapdagon 8 Gen processor",
      "warrenty": "12 Months Warrenty",
      "price": "68,590",
      "delivery_type": "Free delivery",
      "quantity": "Only few left",
      "bank_offer": "Bank Offer",
      "exchange": ""
  }
]